const {webkit}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const {spawn}=require('node:child_process');let qaServer;

(async()=>{
 qaServer=spawn('python',['serve.py','--port','8765'],{cwd:root,stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{qaServer.stdout.once('data',resolve);qaServer.once('error',reject);qaServer.once('exit',c=>reject(new Error('QA server exited '+c)));});
 const report={engine:'Playwright WebKit',realIPhoneTest:false,checks:[],limitations:['使用 Safari 的 WebKit 引擎和 iPhone 尺寸模拟，未在真实 iPhone 或 ChatGPT 内置浏览器设备上运行。','发音按钮的调用已检查；实际可听发音取决于设备的英语语音。']};
 const browser=await webkit.launch({headless:true,...(process.env.WEBKIT_QA_EXECUTABLE?{executablePath:process.env.WEBKIT_QA_EXECUTABLE}:{})});
 const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});let page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765/');await page.waitForSelector('h1');assert.match(await page.locator('h1').textContent(),/Learning in a Changing World/);
 await page.screenshot({path:path.join(root,'qa/iphone-reading.png'),fullPage:false});report.checks.push('HTTP startup and Day 1 rendering');
 const targets=await page.locator('.target button.word').evaluateAll(bs=>[...new Set(bs.map(b=>b.dataset.lemma))]);assert.equal(targets.length,50);assert.equal(await page.locator('.paragraph').count(),5);assert.equal(await page.locator('.english + .chinese').count(),5);report.checks.push('50 highlighted Day 1 targets and English/Chinese paragraph alternation');
 const dimensions=async()=>page.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth,reader:document.getElementById('reader').getBoundingClientRect().width}));for(const width of [320,375,390,430,768,1440]){await page.setViewportSize({width,height:844});let s=await dimensions();assert.ok(s.scroll<=s.w,`Horizontal overflow at ${width}: ${JSON.stringify(s)}`);}report.checks.push('No horizontal overflow at widths 320, 375, 390, 430, 768, 1440');await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>{window.__spoken='';Object.defineProperty(window,'speechSynthesis',{configurable:true,value:{cancel(){},getVoices(){return[];},speak(u){window.__spoken=u.text;}}});});await page.locator('button[data-word="mitigate"]').first().click();assert.equal(await page.evaluate(()=>window.__spoken),'mitigate');report.checks.push('Target word automatically speaks when dictionary opens');await page.waitForSelector('#dictionary[open]');assert.equal(await page.locator('#dict-word').textContent(),'mitigate');assert.match(await page.locator('#dict-content').textContent(),/mitigate the risk/);let rect=await page.locator('#dictionary').boundingBox();assert.ok(rect.x>=0&&rect.x+rect.width<=390&&rect.y>=0&&rect.y+rect.height<=845);await page.screenshot({path:path.join(root,'qa/iphone-dictionary.png')});report.checks.push('Target dictionary with IPA, POS, sense, collocation, context and bounded mobile sheet');
 await page.evaluate(()=>{window.__spoken='';Object.defineProperty(window,'speechSynthesis',{configurable:true,value:{cancel(){},getVoices(){return[];},speak(u){window.__spoken=u.text;}}});});await page.locator('.sound').click();assert.equal(await page.evaluate(()=>window.__spoken),'mitigate');report.checks.push('SpeechSynthesis utterance dispatched from speaker button');await page.locator('[data-close="dictionary"]').click();
 await page.locator('button[data-word="world"]').first().click();assert.equal(await page.locator('#dict-word').textContent(),'world');assert.equal(await page.evaluate(()=>window.__spoken),'world');assert.ok((await page.locator('.phonetic').textContent()).length>2);await page.locator('[data-close="dictionary"]').click();report.checks.push('Ordinary non-target word dictionary');
 await page.locator('button[data-word="students"]').first().click();assert.equal(await page.locator('#dict-word').textContent(),'student');assert.equal(await page.evaluate(()=>window.__spoken),'student');report.checks.push('Ordinary words and inflections automatically speak the lemma');assert.match(await page.locator('.form-note').textContent(),/复数/);await page.locator('[data-close="dictionary"]').click();report.checks.push('Plural students → student with form note');
 await page.locator('#next').click();await page.waitForFunction(()=>location.hash==='#day=2');await page.locator('#contents').click();assert.equal(await page.locator('#toc-list button').count(),26);await page.locator('#toc-list button').last().click();await page.waitForFunction(()=>location.hash==='#day=26');assert.match(await page.locator('.word-count').textContent(),/39 words/);assert.ok(await page.locator('#next').isDisabled());report.checks.push('26-entry contents, next navigation, final chapter 39 words, final-next disabled');
 for(let day=1;day<=26;day++){await page.goto('http://127.0.0.1:8765/#day='+day);await page.waitForFunction(d=>document.querySelector('.day-label')?.textContent==='DAY '+d&&document.querySelector('#reader').getAttribute('aria-busy')==='false',day);assert.equal(await page.locator('.paragraph').count(),5);const bad=await page.evaluate(()=>{const d=document.documentElement;return d.scrollWidth>innerWidth});assert.ok(!bad);const targetCount=await page.locator('.target button.word').evaluateAll(bs=>new Set(bs.map(b=>b.dataset.lemma)).size);assert.equal(targetCount,day===26?39:50);}report.checks.push('All 26 chapters render, target highlights correct, one article in DOM, no overflow');
 await page.goto('http://127.0.0.1:8765/#day=12');await page.waitForFunction(()=>document.querySelector('.day-label')?.textContent==='DAY 12');await page.evaluate(()=>scrollTo(0,1200));await page.waitForFunction(()=>JSON.parse(localStorage.getItem('cet6-reading-v1')).positions['12']>1000);await page.reload();await page.waitForFunction(()=>window.scrollY>1000);assert.match(await page.locator('.day-label').textContent(),/12/);report.checks.push('Reading chapter and scroll position survive reload');
 await page.waitForFunction(async()=>!!(await navigator.serviceWorker.ready));console.log('Offline cache diagnostic:',await page.evaluate(async()=>({keys:await caches.keys(),hit:!!(await caches.match(new URL('data/articles/day-013.json',document.baseURI).href)),controller:!!navigator.serviceWorker.controller})));await context.setOffline(true);await page.locator('#next').click();await page.waitForFunction(()=>document.querySelector('.day-label')?.textContent==='DAY 13');report.checks.push('Cached next chapter loads with the network offline');await context.setOffline(false);
 const fileContext=await browser.newContext({viewport:{width:390,height:844}}),filePage=await fileContext.newPage();filePage.on('pageerror',e=>errors.push(e.message));await filePage.goto('file://'+path.join(root,'dist/index.html'));await filePage.waitForSelector('h1');await filePage.locator('#contents').click();await filePage.locator('#toc-list button').last().click();await filePage.waitForFunction(()=>document.querySelector('.day-label')?.textContent==='DAY 26');await filePage.locator('button[data-word="recipe"]').click();assert.equal(await filePage.locator('#dict-word').textContent(),'recipe');report.checks.push('Direct file:// opening, lazy offline chapters and dictionary work without a server');
 assert.deepEqual(errors,[]);report.javascriptErrors=errors;report.passed=true;fs.writeFileSync(path.join(root,'BROWSER-QA.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();qaServer.kill();
})().catch(e=>{console.error(e);qaServer?.kill();process.exit(1);});
