'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const root=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const rows=read('sources/cet_full_list.json')['四六级词汇词频排序表'],expected=new Set(rows.map(r=>r['单词'].trim().toLowerCase())),vocab=read('dist/data/vocabulary.json'),manifest=read('dist/data/manifest.json'),dict=read('dist/data/dictionary.json'),groups=read('sources/full-groups.json'),audit=read('sources/data-audit.json');
assert.equal(vocab.length,expected.size);assert.equal(new Set(vocab.map(w=>w.word)).size,expected.size);for(const w of vocab)assert.ok(expected.has(w.word));assert.equal(manifest.scope,'entire-source');assert.equal(manifest.totalWords,expected.size);assert.equal(manifest.totalArticles,Math.ceil(expected.size/50));assert.equal(audit.totalTargetWords,expected.size);const files=fs.readdirSync(path.join(root,'dist/data/articles')).filter(f=>f.endsWith('.json'));assert.equal(files.length,manifest.totalArticles);
const assigned=[],countsBad=[],absent=[],glossMissing=[],phonMissing=[],posMissing=[],dictionaryGaps=[],paragraphBad=[],shortArticles=[],titles=new Set();const escape=w=>w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
for(let i=0;i<manifest.articles.length;i++){
 const m=manifest.articles[i],a=read('dist/'+m.path),day=i+1,n=day===manifest.totalArticles?expected.size-i*50:50;assert.equal(m.day,day);assert.equal(a.day,day);assert.equal(a.title,m.title);assert.ok(!titles.has(a.title),'Duplicate title '+a.title);titles.add(a.title);assert.deepEqual(a.targetWords.map(t=>t.word),groups[i]);assert.equal(a.targetWords.length,m.targetCount);if(a.targetWords.length!==n)countsBad.push(day);assert.equal(a.previous,i?i:null);assert.equal(m.previous,a.previous);assert.equal(a.next,day<manifest.totalArticles?day+1:null);assert.equal(m.next,a.next);assert.ok(a.paragraphs.length>=3&&a.paragraphs.length<=10);
 const text=a.paragraphs.map(p=>p.en).join(' '),words=[...text.matchAll(/[A-Za-zÀ-ÖØ-öø-ÿ]+(?:['’][A-Za-zÀ-ÖØ-öø-ÿ]+)?/g)];if(words.length<250&&day!==manifest.totalArticles)shortArticles.push({day,words:words.length});
 for(const t of a.targetWords){assigned.push(t.word);assert.ok(expected.has(t.word),'Non-source target '+t.word);const re=new RegExp('(?<![A-Za-zÀ-ÖØ-öø-ÿ])'+escape(t.word)+'(?![A-Za-zÀ-ÖØ-öø-ÿ])','i');if(!re.test(text))absent.push({day,word:t.word});if(!t.gloss||!/[\u3400-\u9fff]/.test(t.gloss))glossMissing.push(t.word);const e=dict.entries[t.word];if(!e?.phonetic)phonMissing.push(t.word);if(!e?.definitions?.some(d=>d.pos&&d.meaning))posMissing.push(t.word);assert.ok(t.context&&text.includes(t.context));assert.ok(Number.isInteger(t.contextParagraph)&&a.paragraphs[t.contextParagraph]&&/[\u3400-\u9fff]/.test(a.paragraphs[t.contextParagraph].zh));}
 for(const p of a.paragraphs){if(!p.en||!p.zh||!/[\u3400-\u9fff]/.test(p.zh))paragraphBad.push(day);assert.ok(!/[\u3400-\u9fff]/.test(p.en));}
 for(const match of words){const token=match[0].toLowerCase().replace(/’/g,"'"),f=dict.forms[token],e=f&&dict.entries[f.lemma];if(!e||!e.phonetic||!e.definitions.some(d=>d.pos&&d.meaning))dictionaryGaps.push({day,token,lemma:f?.lemma});}
 assert.ok(fs.existsSync(path.join(root,'dist',m.path.replace('.json','.js'))));
}
const counts=new Map();for(const w of assigned)counts.set(w,(counts.get(w)||0)+1);const duplicate=[...counts].filter(([w,n])=>n>1),missing=[...expected].filter(w=>!counts.has(w));assert.equal(dict.forms.studied.lemma,'study');assert.equal(dict.forms.studying.lemma,'study');assert.equal(dict.forms.regulations.lemma,'regulation');assert.equal(dict.forms.largest.lemma,'large');
const app=fs.readFileSync(path.join(root,'dist/assets/app.js'),'utf8');assert.ok(app.includes('if(!speak.disabled)speak.onclick()'));assert.ok(app.includes('chapterLabel(day)'));assert.ok(fs.existsSync(path.join(root,'dist/assets/annotations.js')));
const report={scope:'Entire cet_full_list.json',sourceRows:rows.length,targetVocabulary:expected.size,articlesGenerated:files.length,wordsAssigned:assigned.length,duplicateTargetWords:duplicate.length,missingTargetWords:missing.length,articlesWithIncorrectTargetCount:countsBad.length,targetWordsMissingFromArticleText:absent.length,targetWordsWithoutChineseGloss:glossMissing.length,targetWordsWithoutPhonetic:phonMissing.length,targetWordsWithoutPOS:posMissing.length,bodyDictionaryGaps:dictionaryGaps.length,paragraphsWithoutTranslation:paragraphBad.length,lastArticleTargetCount:manifest.articles.at(-1).targetCount,articleJSONValid:true,manifestConsistent:true,chapterNumbersContinuous:true,navigationCorrect:true,allTargetsFromSource:true,firstArticleUsesSourceGroup:true,autoplayCodePresent:true,annotationToolsPresent:true,dictionaryEntries:Object.keys(dict.entries).length,articleSurfaceForms:Object.keys(dict.forms).length,shortArticleWarnings:shortArticles,errors:{duplicate,missing,countsBad,absent,glossMissing,phonMissing,posMissing,dictionaryGaps,paragraphBad}};
fs.writeFileSync(path.join(root,'VALIDATION.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if([duplicate,missing,countsBad,absent,glossMissing,phonMissing,posMissing,dictionaryGaps,paragraphBad].some(a=>a.length))process.exitCode=1;
