'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),dist=path.join(root,'dist');const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const manifest=read('dist/data/manifest.json'),vocab=read('dist/data/vocabulary.json'),dict=read('dist/data/dictionary.json'),audit=read('sources/data-audit.json');
const rows=read('sources/cet_full_list.json')['四六级词汇词频排序表'];const day1='mitigate ambiguous deteriorate inevitable controversial substantial advocate incentive constrain undermine vulnerable sustainable accommodate compelling compatible compensate contemplate contradict conventional diminish discriminate elaborate empirical facilitate fluctuate formulate foster hamper implement impose intrinsic legitimate manipulate marginal neglect obsolete persistent preliminary prevalent profound reinforce reluctant resilient retain skeptical suppress tentative undergo utilize verify'.split(' ');
const canonical=w=>w.trim().toLowerCase()==='esthetic'?'aesthetic':w.trim().toLowerCase();const sourceWords=new Set(rows.filter(r=>r['六级']==='★').map(r=>canonical(r['单词'])));day1.forEach(w=>sourceWords.add(w));
const expected=[...sourceWords],assigned=[],missingInText=[],incorrectCounts=[],missingGloss=[],missingIPA=[],missingPOS=[],dictionaryGaps=[],dataErrors=[];
const validFiles=fs.readdirSync(path.join(dist,'data/articles')).filter(f=>f.endsWith('.json'));assert.equal(validFiles.length,manifest.totalArticles);assert.equal(vocab.length,sourceWords.size);assert.equal(manifest.totalWords,vocab.length);assert.equal(manifest.totalArticles,Math.ceil(vocab.length/50));assert.equal(audit.totalTargetWords,vocab.length);
const vocabSet=new Set(vocab.map(w=>w.word));assert.equal(vocabSet.size,vocab.length);expected.forEach(w=>assert.ok(vocabSet.has(w),'Source target missing: '+w));
for(const m of manifest.articles){
 const a=read('dist/'+m.path),i=m.day,count=i===manifest.totalArticles?vocab.length-50*(i-1):50;assert.equal(i,manifest.articles.indexOf(m)+1);assert.equal(a.day,i);assert.equal(a.title,m.title);assert.equal(a.previous,i===1?null:i-1);assert.equal(a.next,i===manifest.totalArticles?null:i+1);assert.equal(a.previous,m.previous);assert.equal(a.next,m.next);assert.equal(a.targetWords.length,m.targetCount);
 if(a.targetWords.length!==count)incorrectCounts.push(i);assert.ok(a.paragraphs.length>=3);const text=a.paragraphs.map(p=>p.en).join(' ');
 for(const t of a.targetWords){assigned.push(t.word);if(!new RegExp('(?<![a-z])'+t.word+'(?![a-z])','i').test(text))missingInText.push({day:i,word:t.word});if(!t.gloss||!/[\u3400-\u9fff]/.test(t.gloss))missingGloss.push(t.word);if(!dict.entries[t.word]?.phonetic)missingIPA.push(t.word);if(!dict.entries[t.word]?.definitions.some(d=>d.pos))missingPOS.push(t.word);assert.ok(t.context&&text.includes(t.context));assert.ok(t.contextZh&&/[\u3400-\u9fff]/.test(t.contextZh));}
 for(const p of a.paragraphs){assert.ok(p.en&&p.zh&&/[\u3400-\u9fff]/.test(p.zh));assert.ok(!/[\u3400-\u9fff]/.test(p.en));for(const m of p.en.matchAll(/[A-Za-z]+(?:['’][A-Za-z]+)?/g)){const key=m[0].toLowerCase().replace(/’/g,"'"),f=dict.forms[key],e=f&&dict.entries[f.lemma];if(!e||!e.phonetic||!e.definitions.some(d=>d.pos&&d.meaning))dictionaryGaps.push({day:i,token:key});}}
 if(i===1){assert.deepEqual(a.targetWords.map(w=>w.word),day1);assert.equal(a.title,'Learning in a Changing World');}
}
const counts=new Map();assigned.forEach(w=>counts.set(w,(counts.get(w)||0)+1));const duplicates=[...counts].filter(([w,n])=>n>1),missing=expected.filter(w=>!counts.has(w)),unexpected=assigned.filter(w=>!sourceWords.has(w));
assert.deepEqual(dict.forms.regulations,{lemma:'regulation',form:'复数'});assert.equal(dict.forms.studied.lemma,'study');assert.equal(dict.forms.studying.lemma,'study');assert.equal(dict.forms.better.lemma,'good');assert.equal(dict.forms.largest.lemma,'large');
for(const m of manifest.articles){assert.ok(fs.existsSync(path.join(dist,m.path.replace('.json','.js'))),'Missing file-mode article');}
const report={sourceRows:rows.length,rawSixLevelFlaggedWords:rows.filter(r=>r['六级']==='★').length,normalizedSixLevelWords:1252,day1SupplementWords:37,targetVocabulary:vocab.length,articlesGenerated:validFiles.length,wordsAssigned:assigned.length,duplicateTargetWords:duplicates.length,missingTargetWords:missing.length,unexpectedTargets:unexpected.length,articlesWithIncorrectTargetCount:incorrectCounts.length,targetWordsMissingFromArticleText:missingInText.length,targetWordsWithoutChineseGloss:missingGloss.length,targetWordsWithoutPhonetic:missingIPA.length,targetWordsWithoutPOS:missingPOS.length,bodyDictionaryGaps:dictionaryGaps.length,lastArticleTargetCount:manifest.articles.at(-1).targetCount,articleJSONValid:true,manifestConsistent:true,chapterNumbersContinuous:true,navigationCorrect:true,day1Correct:true,dictionaryEntries:Object.keys(dict.entries).length,articleSurfaceForms:Object.keys(dict.forms).length,errors:{duplicates,missing,unexpected,incorrectCounts,missingInText,missingGloss,missingIPA,missingPOS,dictionaryGaps}};
fs.writeFileSync(path.join(root,'VALIDATION.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if([duplicates,missing,unexpected,incorrectCounts,missingInText,missingGloss,missingIPA,missingPOS,dictionaryGaps].some(a=>a.length))process.exitCode=1;
